# this is what the docs say to do, but can't get to work...
# pulling the 5-slim image and committing changes instead

FROM java:7

ADD transportation-service /transportation-service
ADD run.sh /

CMD /run.sh

# default port
EXPOSE 5001
